#28 Feature:  Implementing landing-page.
atlp-rwanda/phantom-fe-elite pull request #13
Opened 2022-04-19 09:37 UTC by Niyonkuru1

What does this PR do?

- Create UI for landing-page

Description of Task to be completed?

- Landing Page UI is created. It includes three components; footer, navbar and LandingPage.  

- It should be responsive.

- It should perfectly resemble to the corresponding design in the mockup

-  UI skeleton for loading displayed

How should this be manually tested?
- Clone the repo
- checkout to branch ft-landing-page-28
- pull the changes by git pull
- install all packages by running npm install
- start app by running npm run start.
-  It should dispaly all contents of the landing page as depicted in the design

Any background context you want to provide?

- [ Work In Progress
 ]; 

What are the relevant pivotal tracker stories?
[Trello Board # 28](https://trello.com/c/7MYeedeR/28-landing-page)

Screenshots (if appropriate)

2022-04-19 20:23 UTC, tysepa approved these changes

2022-04-19 20:26 UTC, PrinceNiyonshuti approved these changes
Looks good

2022-04-20 17:23 UTC, PatrickNiyogitare28 requested changes
Remove the commented source codes then we be able to merge the work

2022-04-20 17:23 UTC, PatrickNiyogitare28 commented on packageDraft.txt
> +//     "react-test-renderer": "^18.0.0",
Can you please try to remove the comments.

2022-04-24 17:39 UTC, Hodal66 approved these changes

2022-04-25 05:02 UTC, PrinceNiyonshuti approved these changes
looks good

2022-04-25 12:15 UTC, PatrickNiyogitare28 commented
Remove the conflicts in this branch

2022-04-27 18:18 UTC, PatrickNiyogitare28 approved these changes

2022-04-30 17:40 UTC, merged