Ft login 29
atlp-rwanda/phantom-fe-elite pull request #16
Opened 2022-04-24 17:40 UTC by Hodal66

2022-04-25 16:00 UTC, tysepa reviewed
make  sure  all conflict are solved well

2022-04-28 20:33 UTC, PrinceNiyonshuti requested changes
work on comments and you will be ready to go

2022-04-28 20:33 UTC, PrinceNiyonshuti commented on src/index.html
> +    <!-- <script src="https://cdn.tailwindcss.com"></script>  -->
remove the CDN as its no longer being used

2022-05-05 18:36 UTC, PatrickNiyogitare28 approved these changes

2022-05-05 18:39 UTC, Niyonkuru1 approved these changes

2022-05-05 18:40 UTC, tysepa approved these changes

2022-05-05 18:41 UTC, merged