#36 Feature: register driver & operator
atlp-rwanda/phantom-fe-elite pull request #17
Opened 2022-04-25 10:02 UTC by rachelakimana

#### What does this PR do?

- Create register page

#### Description of Task to be completed? 

- Allow an administrator to register a new driver or a new operator.

- Form validation and display appropriate error messages on unsuccessful attempts

- Responsiveness of the

#### How should this be manually tested?

- Clone the repo

- checkout to branch ``ft-register-36``

- Run `npm install` to install modules

- Run `npm  run start` to start the development server

- On the landing page click on the Sign up menu

#### What are the relevant Pivotal Tracker/trello stories?

- https://trello.com/c/Sd4qDC5s/36-register-drivers-operators

#### Questions:

- N/A

2022-04-25 10:36 UTC, PrinceNiyonshuti requested changes
looks good and as additional remember to provide the expected results as it is in frontend and resolve the conflicts that have been occured

2022-04-25 10:36 UTC, PrinceNiyonshuti commented on src/component/__test__/RegisterPage.test.js
> +  //   await user.type(screen.getByTestId("password-input"), "N#@!Pass");
remember to remove the commented codes which are no longer in use

2022-04-25 11:17 UTC, tysepa approved these changes
Please work on that collection @PrinceNiyonshuti has been telling you to collect but you working good

2022-04-25 12:13 UTC, PatrickNiyogitare28 reviewed
Resolve the conflicts as well

2022-04-27 08:49 UTC, rachelakimana commented
@PrinceNiyonshuti @PatrickNiyogitare28 
you can review my PR i have done with the requested changes

2022-04-27 20:06 UTC, PatrickNiyogitare28 requested changes
I'm learning it and get weback compilation errors.

2022-04-28 11:28 UTC, PrinceNiyonshuti approved these changes
looks good

2022-05-02 15:58 UTC, Xldivin approved these changes

2022-05-02 17:13 UTC, PatrickNiyogitare28 requested changes
Can you slightly fix these issues? The header should be responsive in your component as well

![image](https://user-images.githubusercontent.com/54368821/166293325-7e04705d-a40e-4f35-9f9d-4fe4d4a7d4ac.png)

2022-05-03 10:30 UTC, rachelakimana commented
@PatrickNiyogitare28 , you can review this PR again, I have done with the request changes

2022-05-03 11:47 UTC, PatrickNiyogitare28 approved these changes

2022-05-03 11:47 UTC, merged