Ft create operator and set permissions 32
atlp-rwanda/phantom-fe-elite pull request #26
Opened 2022-05-11 10:52 UTC by Niyonkuru1

2022-05-12 11:55 UTC, Niyonkuru1 commented
### What does this PR do?
- CRUD operations for operator
- Setting them a role
### Description of Task to be completed?
As an admin, I want to create, update, and delete operators and set them a roles so that they perform the task they are assigned to only.

- The admin should be able to create, update, and delete a operator.
- The admin should be able to view a paginated list of operators in the system.

- Skeleton UIs/screen are/is shown when the page loads/is loading.
 - The page is responsive.
- Appropriate error messages are displayed on unsuccessful attempts
### How should this be manually tested?
`Clone the repo`

`checkout` to branch `ft-create-operator-and-set-permissions-32
`

pull the changes by `git pull`

install all packages by `running npm install`

start app by running `npm run start`

### Any background context you want to provide?
N/A

### What are the relevant pivotal tracker stories?
[Trello Board](https://trello.com/c/OlZ7LyxG/32-create-operator-set-permissions)

Screenshots (if appropriate)

2022-05-12 22:29 UTC, tysepa approved these changes

2022-05-16 07:18 UTC, PrinceNiyonshuti requested changes
please remove the unused codes that are commented

2022-05-16 07:18 UTC, PrinceNiyonshuti commented on src/dashboard/Admin.js
> +// import {
remember to remove the unused codes

2022-05-16 07:18 UTC, PrinceNiyonshuti commented on src/dashboard/ErrorMessage.js
> +// const ErrorMessage = () => {
the same here with unused codes

2022-05-16 07:18 UTC, PrinceNiyonshuti commented on src/dashboard/FormModal.js
> +//   return (
same here and the rest of commented or unused codes

2022-05-16 09:53 UTC, Xldivin approved these changes

2022-05-19 21:28 UTC, tysepa approved these changes
working good

2022-05-23 07:08 UTC, PrinceNiyonshuti approved these changes
looks good

2022-05-23 11:35 UTC, PatrickNiyogitare28 requested changes
Remove comments every where in your codebase

2022-05-23 11:35 UTC, PatrickNiyogitare28 commented on src/Routes/LandingPage.js
> +	// 						<h1 className="text-textBluePhant font-bold leading-9 text-3xl sm:text-4xl font-Montserrat">
Remember to remove comments for the best code quality

2022-05-25 06:19 UTC, Hodal66 approved these changes

2022-05-26 07:04 UTC, PatrickNiyogitare28 approved these changes

2022-05-26 07:04 UTC, merged