#9 Feature: crud operations for driver
atlp-rwanda/phantom-fe-elite pull request #28
Opened 2022-05-13 09:08 UTC by tysepa

What does this PR do?

CRUD operations for Driver
Setting them a role
Description of Task to be completed?
As an admin, I want to create, update, and delete Driver and set their roles so that they perform the task they are assigned to only.

The admin should be able to create, update, and delete a Driver.

The admin should be able to view a paginated list of drivers in the system.

Skeleton UIs/screen are/is shown when the page loads/is loading.

The page is responsive.

How should this be manually tested?
Clone the repo

checkout to branch `ft-crud-operations-for-driver-9`

pull the changes by `git pull`

install all packages by running `npm install`

start an app by running `npm run start`

Any background context you want to provide?
N/A

What are the relevant pivotal tracker stories?
[Trello Board](https://trello.com/c/eRqrQ2Tl/9-create-driver-set-permissions)

Screenshots (if appropriate)

2022-05-20 07:09 UTC, PrinceNiyonshuti requested changes
why the node modules were uploaded and what are they serving in this scenario

2022-05-27 05:28 UTC, Niyonkuru1 approved these changes
Looks good.

2022-05-27 10:01 UTC, Xldivin approved these changes

2022-05-27 10:02 UTC, PrinceNiyonshuti approved these changes
Looks good

2022-05-27 18:22 UTC, merged