#34 Feature: routes CRUD operations for operator
atlp-rwanda/phantom-fe-elite pull request #29
Opened 2022-05-13 10:26 UTC by Salim-54

### What does this PR do?
- routes CRUD operations for operator
### Description of Task to be completed?

As an operator, I want to create routes so that buses can travel in pre-defined routes. As an operator, I want to create routes so that users can view in pre-defined routes.

- The operator should be able to create, delete, and update a route.
- The operator should be able to view a paginated list of routes in the system.
- The users should be able to view a route's details
- Skeleton UIs/screen are/is shown when the page loads/is loading.
- The page is responsive.
- The page is responsive.

### How should this be manually tested?
`Clone the repo`

`checkout` to branch `ft-operator-crud-for-routes-34`

pull the changes by `git pull`

install all packages by `running npm install`

start app by running `npm run start`

### Any background context you want to provide?
N/A

### What are the relevant pivotal tracker stories?
[[Trello Board](https://trello.com/c/TgBkFOb5/34-crud-operations-for-routes)
![Screenshot (302)](https://user-images.githubusercontent.com/81898585/168264790-d51650c2-747f-43aa-95f5-5cf9101b38d1.png)
![Screenshot (301)](https://user-images.githubusercontent.com/81898585/168264801-dcda7953-4239-4d94-925a-f6ec13f6e88d.png)
![Screenshot (303)](https://user-images.githubusercontent.com/81898585/168264805-c4b1e7fe-3da4-4b80-bef9-12c4e9dfd782.png)

2022-05-13 13:02 UTC, PrinceNiyonshuti approved these changes
looks good

2022-05-16 15:29 UTC, tysepa approved these changes

2022-05-20 12:49 UTC, Xldivin approved these changes

2022-05-26 07:34 UTC, PatrickNiyogitare28 requested changes
The work meets expectations just remove those commented source codes

2022-05-26 07:34 UTC, PatrickNiyogitare28 commented on src/component/UpdateRouteModal.js
> +                // defaultValue={`${destinationUpdate}`}
Remove these comments for the best code quality

2022-05-26 07:34 UTC, Xldivin approved these changes

2022-05-26 07:35 UTC, PatrickNiyogitare28 commented
Finally rebase your branch on `develop` to remove the conflicts

2022-05-26 08:28 UTC, Hodal66 approved these changes

2022-05-26 10:02 UTC, tysepa approved these changes

2022-05-27 05:34 UTC, Niyonkuru1 approved these changes
Looks great!

2022-05-27 09:57 UTC, PatrickNiyogitare28 approved these changes

2022-05-27 09:58 UTC, PatrickNiyogitare28 approved these changes

2022-05-27 10:00 UTC, merged