chore(crud-for-routes):set integration
atlp-rwanda/phantom-fe-elite pull request #44
Opened 2022-07-11 07:36 UTC by Hodal66

### What does this PR do?
CRUD operations for routes (Integrestion)

**Description of Task to be completed?**
As an operator, I want to create routes so that buses can travel in pre-defined routes. As an operator, I want to create routes so that users can view in pre-defined routes.

**How should this be manually tested?**

Clone the repo

checkout to branch  `ch-crud-operation-for-routes-integration-21`

pull the changes by using

 `git pull`

**install all packages by running**

` npm install`

**start the app by running**

` npm run start`

Any background context you want to provide?
N/A

What are the relevant pivotal tracker stories?

https://trello.com/c/DzW1ynfk/21-crud-operations-for-routes

2022-07-17 21:12 UTC, PatrickNiyogitare28 requested changes
Get the conflicts resolved

2022-07-18 07:27 UTC, PrinceNiyonshuti approved these changes
Looks Good

2022-07-18 10:30 UTC, tysepa approved these changes

2022-07-18 10:31 UTC, Xldivin approved these changes

2022-07-18 10:34 UTC, Hodal66 commented
> Get the conflicts resolved

Conflicts resolved

2022-07-18 11:23 UTC, PatrickNiyogitare28 approved these changes

2022-07-18 11:24 UTC, merged